### ISSUE TITLE
feature request: add cv::putText

### ISSUE THREAD

**Issue by goloskokovic** [zchrissirhcz/smallcv#12]
It would make sence to have class of the object or ID next to the bounding box out of ncnn.

What is the workaround to put text on the image for now?
https://github.com/nothings/stb/blob/master/stb_easy_font.h

**Comment by zchrissirhcz** [comment]
Currently I don't have time to implement a good `cv::putText()`.

The `stb_image_font.h` seems not suggested by stb author(s), maybe  stb_truetype.h is more suitable. 

Another option is using ncnn, provided the `draw_text_c3()` APIs:

https://github.com/Tencent/ncnn/blob/master/src/mat.h#L709-L721

**Comment by zchrissirhcz** [comment]
Support `cv::putText()` now.
