### ISSUE TITLE
python bind need.

### ISSUE THREAD

**Issue by novioleo** [zchrissirhcz/smallcv#4]

**Comment by zchrissirhcz** [comment]
@novioleo 
Hi, thanks for advice.

I think pybind11 is ok for SmallCV's python binding, but right now SmallCV lacks many basic functions such as draw rect, putText. I would consider do python binding after these basic functions are implemented.

You may also try do python binding using pybind11 by yourself, just for imread/imwrite/imshow. But if just for these 3 functions, I think pip/conda install opencv python `cv2` module would ok enough.

**Comment by novioleo** [comment]
tks 4 ur reply------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Zhuo&amp;nbsp;Zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月14日(星期一) 下午2:51
收件人:&nbsp;&quot;zchrissirhcz/smallcv&quot;<smallcv@noreply.github.com&gt;;
抄送:&nbsp;&quot;Tao Luo&quot;<744351893@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zchrissirhcz/smallcv] python bind need. (#4)
