### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by yzfly** [zchrissirhcz/smallcv#7]
Hello, when I run smallcv example, g++ gave me the errors:

undefined reference to `sv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Are there other steps to use smallcv except just    #include "smallcv.hpp" ?

**Comment by zchrissirhcz** [comment]
@yzfly  Hi, I build and run this project with (on linux, for example)
```bash
cd build
./linux-x64.sh
cd linux-x64
cp ../../assets/* ./
./basic_example
```

Can you please provide your platform, your steps, to reproduce that link error? And could you try the above pasted method?

**Comment by zchrissirhcz** [comment]
Note that the examples rely on ncnn thus I firstly compiled and intalled ncnn.

**Comment by yzfly** [comment]
Thank you for your help!
It was my fault. I thought it could be used to read jpg images directly just like 'stb_image.h'.
